# ─────────────────────────────────────────
# SERVER
# ─────────────────────────────────────────
server.port=8080

# ─────────────────────────────────────────
# KAFKA
# ─────────────────────────────────────────
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=cooldown-engine-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all

# ─────────────────────────────────────────
# TOPICS
# ─────────────────────────────────────────
kafka.topics.teleport-events=teleport-events
kafka.topics.cooldown-results=cooldown-results

# ─────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────
logging.level.com.pokego=DEBUG
logging.level.org.apache.kafka=WARN